### ISSUE TITLE
String Length

### ISSUE THREAD

**Issue by alimoosavi15** [robballou/atom-randomstring#1]
It would be nice if we could choose the generated string length in a settings page.

**Comment by robballou** [comment]
I've added support for length and charset options. Check the README. If that works for other people, I'll push it into a release: https://github.com/robballou/atom-randomstring/blob/master/README.md

Thanks!

**Comment by alimoosavi15** [comment]
Thanks! How should I pass those configurations to the package?

**Comment by alimoosavi15** [comment]
Thanks! I updated the package and added the config options in Atom's config file but configurations are not taking effect.

**Comment by robballou** [comment]
I think this was fixed with #2 so I will publish this.
